// <auto-generated />
using LegoPartsRegister.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LegoPartsRegister.Migrations.Pg.Migrations
{
	[DbContext( typeof( AppDbContext ) )]
	[Migration( "20211222140646_AddedUserModel" )]
	partial class AddedUserModel
	{
		protected override void BuildTargetModel( ModelBuilder modelBuilder )
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation( "ProductVersion", "6.0.1" )
				.HasAnnotation( "Relational:MaxIdentifierLength", 63 );

			NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns( modelBuilder );

			modelBuilder.Entity( "LegoPartsRegister.Domain.Models.UserModel", b =>
				 {
					 b.Property<int>( "Id" )
						 .ValueGeneratedOnAdd()
						 .HasColumnType( "integer" );

					 NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn( b.Property<int>( "Id" ) );

					 b.Property<string>( "PasswordHash" )
						 .IsRequired()
						 .HasColumnType( "text" );

					 b.Property<string>( "Username" )
						 .IsRequired()
						 .HasMaxLength( 32 )
						 .HasColumnType( "character varying(32)" );

					 b.Property<string>( "Uuid" )
						 .IsRequired()
						 .HasMaxLength( 24 )
						 .HasColumnType( "character varying(24)" );

					 b.HasKey( "Id" );

					 b.HasIndex( "Username" )
						 .IsUnique();

					 b.HasIndex( "Uuid" )
						 .IsUnique();

					 b.ToTable( "Users" );
				 } );
#pragma warning restore 612, 618
		}
	}
}
