// <auto-generated />
using LegoPartsRegister.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LegoPartsRegister.Migrations.MsSql.Migrations
{
	[DbContext( typeof( AppDbContext ) )]
	[Migration( "20211222184805_AddedUserModel" )]
	partial class AddedUserModel
	{
		protected override void BuildTargetModel( ModelBuilder modelBuilder )
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation( "ProductVersion", "6.0.1" )
				.HasAnnotation( "Relational:MaxIdentifierLength", 128 );

			SqlServerModelBuilderExtensions.UseIdentityColumns( modelBuilder, 1L, 1 );

			modelBuilder.Entity( "LegoPartsRegister.Domain.Models.UserModel", b =>
				 {
					 b.Property<int>( "Id" )
						 .ValueGeneratedOnAdd()
						 .HasColumnType( "int" );

					 SqlServerPropertyBuilderExtensions.UseIdentityColumn( b.Property<int>( "Id" ), 1L, 1 );

					 b.Property<string>( "PasswordHash" )
						 .IsRequired()
						 .HasColumnType( "nvarchar(max)" );

					 b.Property<string>( "Username" )
						 .IsRequired()
						 .HasMaxLength( 32 )
						 .HasColumnType( "nvarchar(32)" );

					 b.Property<string>( "Uuid" )
						 .IsRequired()
						 .HasMaxLength( 24 )
						 .HasColumnType( "nvarchar(24)" );

					 b.HasKey( "Id" );

					 b.HasIndex( "Username" )
						 .IsUnique();

					 b.HasIndex( "Uuid" )
						 .IsUnique();

					 b.ToTable( "Users" );
				 } );
#pragma warning restore 612, 618
		}
	}
}
